"""edit card-cart edit

Revision ID: 01b8ff3ad928
Revises: c888c36454d0
Create Date: 2025-11-17 01:49:05.166495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b8ff3ad928'
down_revision: Union[str, None] = 'c888c36454d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_items_card_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'])
    op.drop_column('cart_items', 'card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_card_id_fkey', 'cart_items', 'carts', ['card_id'], ['id'])
    op.drop_column('cart_items', 'cart_id')
    # ### end Alembic commands ###
