"""edit cart

Revision ID: e01493c7f9b4
Revises: 
Create Date: 2025-11-16 22:39:09.965245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01493c7f9b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_id', table_name='cart')
    op.drop_table('cart')
    op.add_column('cart_items', sa.Column('card_id', sa.Integer(), nullable=True))
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'carts', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'created_at')
    op.drop_column('cart_items', 'card_id')
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cart_pkey')
    )
    op.create_index('ix_cart_id', 'cart', ['id'], unique=False)
    # ### end Alembic commands ###
